import { CATEGORIES } from "@/shared/constants";

const IMG_BASE = "/assets/img/productos/complementos";

export const complementos = [
  {
    title: "Petit",
    description: "",
    images: [`${IMG_BASE}/petit.jpeg`],
    category: CATEGORIES["complementos"],
    price: { ars: { base: 10000, aument: 0 }, usd: { base: 10, aument: 0 } },
    variant: { name: "Presentación", options: ["Default"] },
  },
  {
    title: "ROCK",
    description: "",
    images: [`${IMG_BASE}/rock.jpeg`],
    category: CATEGORIES["complementos"],
    price: { ars: { base: 15000, aument: 0 }, usd: { base: 15, aument: 0 } },
    variant: { name: "Presentación", options: ["Default"] },
  },
  {
    title: "Glow",
    description: "",
    images: [`${IMG_BASE}/glow.jpeg`],
    category: CATEGORIES["complementos"],
    price: { ars: { base: 20000, aument: 0 }, usd: { base: 20, aument: 0 } },
    variant: { name: "Presentación", options: ["Default"] },
  },
  {
    title: "Iris XL",
    description: "",
    // No hay archivo "iris-xl" todavía: usar Iris.jpeg como placeholder.
    images: [`${IMG_BASE}/Iris.jpeg`],
    category: CATEGORIES["complementos"],
    price: { ars: { base: 51000, aument: 0 }, usd: { base: 51, aument: 0 } },
    variant: { name: "Presentación", options: ["Default"] },
  },
  {
    title: "IRIS",
    description: "",
    images: [`${IMG_BASE}/Iris.jpeg`],
    category: CATEGORIES["complementos"],
    price: { ars: { base: 31500, aument: 0 }, usd: { base: 32, aument: 0 } },
    variant: { name: "Presentación", options: ["Default"] },
  },
  {
    title: "Anello",
    description: "",
    images: [`${IMG_BASE}/anello.jpeg`],
    category: CATEGORIES["complementos"],
    price: { ars: { base: 12000, aument: 0 }, usd: { base: 12, aument: 0 } },
    variant: { name: "Presentación", options: ["Default"] },
  },
  {
    title: "Cristalito",
    description: "",
    images: [`${IMG_BASE}/cristalito.jpeg`],
    category: CATEGORIES["complementos"],
    price: { ars: { base: 15000, aument: 0 }, usd: { base: 15, aument: 0 } },
    variant: { name: "Presentación", options: ["Default"] },
  },
  {
    title: "Wild",
    description: "",
    images: [`${IMG_BASE}/wild.jpeg`],
    category: CATEGORIES["complementos"],
    price: { ars: { base: 20000, aument: 0 }, usd: { base: 20, aument: 0 } },
    variant: { name: "Presentación", options: ["Default"] },
  },
  {
    title: "Silver jar",
    description: "",
    images: [`${IMG_BASE}/silverjar.jpeg`],
    category: CATEGORIES["complementos"],
    price: { ars: { base: 8500, aument: 0 }, usd: { base: 9, aument: 0 } },
    variant: { name: "Presentación", options: ["Default"] },
  },
  {
    title: "Natale",
    description: "",
    images: [`${IMG_BASE}/natale.jpeg`],
    category: CATEGORIES["complementos"],
    price: { ars: { base: 23000, aument: 0 }, usd: { base: 23, aument: 0 } },
    variant: { name: "Presentación", options: ["Default"] },
  },
  {
    title: "Velón Raggio",
    description: "",
    images: [`${IMG_BASE}/velonraggio.jpeg`],
    category: CATEGORIES["complementos"],
    price: { ars: { base: 48000, aument: 0 }, usd: { base: 48, aument: 0 } },
    variant: { name: "Presentación", options: ["Default"] },
  },
  {
    title: "Velón Chiara",
    description: "",
    images: [`${IMG_BASE}/velonchiara.jpeg`],
    category: CATEGORIES["complementos"],
    price: { ars: { base: 48000, aument: 0 }, usd: { base: 48, aument: 0 } },
    variant: { name: "Presentación", options: ["Default"] },
  },
];
