version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.73.1
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
      - /home/santiago/dev/n8n/n8n-nodes-petstore:/home/node/.n8n/custom/node_modules/petstore

volumes:
  n8n_data:
