name: Build Next.js Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - "apps/www/**"
      - "Dockerfile"                  # <- dispara si cambia el Dockerfile raíz
      - ".github/workflows/build-frontend-image.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Assert Dockerfile exists
        run: test -f ./Dockerfile || (echo "No se encontró ./Dockerfile" && exit 1)

      - name: Build and push (Next.js)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile           # <- volvemos a la raíz
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/floreria-nextjs:latest