name: Build Next.js Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - "apps/www/**"
      - ".github/workflows/build-frontend-image.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # QEMU es opcional si solo construís amd64; lo dejamos por si necesitás multi-arch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (Next.js)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/www/Dockerfile   # <-- Asegurate de tener este Dockerfile; si está en otra ruta, actualizá este valor
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/floreria-nextjs:latest
          # platforms: linux/amd64,linux/arm64   # descomentá si querés multi-arch