# .github/workflows/build-frontend-image.yml
name: Build Next.js Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - "apps/www/**"
      - "Dockerfile"
      - ".github/workflows/build-frontend-image.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: build-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Deploy-Production:
    runs-on: ubuntu-24.04
    environment: TOKEN_VERCEL
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Assert Dockerfile exists
        run: test -f ./Dockerfile || (echo "No se encontró ./Dockerfile" && exit 1)
      - name: Check NEXT_PUBLIC_MEDUSA_BACKEND_URL
        env:
          NEXT_PUBLIC_MEDUSA_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_MEDUSA_BACKEND_URL }} # o vars.
        run: |
          if [ -z "$NEXT_PUBLIC_MEDUSA_BACKEND_URL" ]; then
            echo "::error::NEXT_PUBLIC_MEDUSA_BACKEND_URL no está definido"; exit 1
          fi      
      - name: Validate required secrets
        env:
          NEXT_TELEMETRY_DISABLED: 1
          NEXT_RUNTIME: nodejs
          DB_URL: ${{ secrets.DB_URL }}
          DB_TOKEN: ${{ secrets.DB_TOKEN }}
          MERCADO_PAGO_TOKEN: ${{ secrets.MERCADO_PAGO_TOKEN }}
          APP_URL: ${{ secrets.APP_URL }}
          S3_URL: ${{ secrets.S3_URL }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_KEY_ID: ${{ secrets.S3_KEY_ID }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
        run: |
          set -e
          for s in DB_URL DB_TOKEN MERCADO_PAGO_TOKEN APP_URL S3_URL S3_BUCKET S3_KEY_ID S3_SECRET PAYLOAD_SECRET; do
            if [ -z "${!s}" ]; then
              echo "::error::Missing secret: $s"
              exit 1
            fi
          done

      - name: Build & Push image
        uses: docker/build-push-action@v6
        env:
          BUILDKIT_PROGRESS: plain
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/floreria-nextjs:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            DB_URL=${{ secrets.DB_URL }}
            DB_TOKEN=${{ secrets.DB_TOKEN }}
            MERCADO_PAGO_TOKEN=${{ secrets.MERCADO_PAGO_TOKEN }}
            APP_URL=${{ secrets.APP_URL }}
            S3_URL=${{ secrets.S3_URL }}
            S3_BUCKET=${{ secrets.S3_BUCKET }}
            S3_KEY_ID=${{ secrets.S3_KEY_ID }}
            S3_SECRET=${{ secrets.S3_SECRET }}
            PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}
            NEXT_PUBLIC_MEDUSA_BACKEND_URL=${{ secrets.NEXT_PUBLIC_MEDUSA_BACKEND_URL }}
          build-args: |
            NEXT_PUBLIC_MEDUSA_BACKEND_URL=${{ vars.NEXT_PUBLIC_MEDUSA_BACKEND_URL }}