name: Build Next.js Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - "apps/www/**"
      - "Dockerfile"
      - ".github/workflows/build-frontend-image.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  Deploy-Production:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/lasfloresdelaimprenta-www:latest
          secrets: |
            DB_URL=${{ secrets.DB_URL }}
            DB_TOKEN=${{ secrets.DB_TOKEN }}
            MERCADO_PAGO_TOKEN=${{ secrets.MERCADO_PAGO_TOKEN }}
            APP_URL=${{ secrets.APP_URL }}
            S3_URL=${{ secrets.S3_URL }}
            S3_BUCKET=${{ secrets.S3_BUCKET }}
            S3_KEY_ID=${{ secrets.S3_KEY_ID }}
            S3_SECRET=${{ secrets.S3_SECRET }}
            PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            MEDUSA_BACKEND_URL=${{ secrets.MEDUSA_BACKEND_URL }}
          build-args: |
            NEXT_PUBLIC_MEDUSA_BACKEND_URL=${{ secrets.MEDUSA_BACKEND_URL }}
